# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2840fedee78a703a0a90f726142fc321c99b15f8c42346de933ceae133a4178e6782e1157f168e4208f83fefd0a11d9982bb38852d42afbbb9a0117c465c931e

test:
  secret_key_base: e4ab4494e324c54a29aac0a22200f188d8677a0e3bf4933bc12b1948e14ee69ff82aa98d8b74f2f386d06408bd1cddea771d75eddc88ead4a085b5dd6b4235d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
