# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95621c97cdb8d02701ce73df1d311d5ecccdee2c0e5230bc58b2df19b722283e4ec2d38af0e354004ce68dbbdf9f0ddb2fea69558acbc03ea63b6acd8f536ba

test:
  secret_key_base: f0922a7d30de45fea3e2250e64e20aa7a7a4f15659ebdfd8aa09d9a837f4fd8d180866cafb44b7b17216bf026860b3d55e38dc377106139910f43453ea83bc84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
